### ISSUE TITLE
Align the SDK to the latest spec in https://cdevents.dev/docs/

### ISSUE THREAD

**Issue by afrittoli** [cdevents/sdk-java#11]
The current SDK has been created to replicate the behaviour of the [old go SDK](https://github.com/cdfoundation/sig-events/tree/main/cde/sdk/go). 
The spec has been since updated, and a new version of the [go SDK](https://github.com/cdevents/sdk-go) is available.

The Java SDK must be aligned to the most recent spec so that moving forward changes to the spec may be easily reflected in the SDK. As this is a relatively large chunk of work, it would be ok to split it into multiple PRs. To avoid having a mid-state SDK we could work off a branch and merge it back into `main` when ready.

**Comment by afrittoli** [comment]
@adamkenihan can this one be closed now that https://github.com/cdevents/sdk-java/pull/14 is merged?

**Comment by afrittoli** [comment]
@adamkenihan @rjalander what version of the spec is the SDK aligned with now?

**Comment by rjalander** [comment]
it is with 0.1.0

**Comment by rjalander** [comment]
Yeah sure, we can close and create one for v0.2.0

**Comment by rjalander** [comment]
The SDK is generated with latest version of spec 0.3.0, https://github.com/cdevents/sdk-java/pull/62 closing this issue.
