### ISSUE TITLE
Support Java Modules

### ISSUE THREAD

**Issue by aalmiray** [cdevents/sdk-java#16]
The codebase currently targets Java 8. [Java Modules](https://en.wikipedia.org/wiki/Java_Platform_Module_System) were added in Java 9, providing benefits to both API designers and consumers. It's possible to add a full module descriptor while remaining Java 8 compatible by using the [ModiTect](https://github.com/moditect/moditect) plugin.

I've personally help more than a dozen projects to migrate to Java modules in this way. I can prepare a PR if the team agrees to move forward with this idea.

**Comment by aalmiray** [comment]
In terms of LTS releases:
- Java 8 supported til 2030
- Java 11 supported til 2023
- Java 17 supported til 2026 (I think)
- Java 21 (coming Sept 2023) supported til 2029

Yes, Java 8 will be supported for much longer than the next 3 LTS releases after it. So far. 

If there are no immediate needs to use syntax and features from newer Java versions I'd say sticking with 8 is the conservative way. 

But at the same time I must recognize recommending to sticking to Java 8 is a selfish deal because as it happens JReleaser 1.x must remain Java 8 compatible and I'd love to integrate it with cdevents-java.

**Comment by afrittoli** [comment]
Yes, [indeed](https://endoflife.date/java), security support for Java 8 is provided until 2030!
I don't know what "active support" means for other releases - it is not available for Java 8, but I don't expect that to be an issue. As long as we have all the language features we need in Java 8, it's fine for me to stay Java 8 compatible.

One of the features that is important that we build soon is code generation - every time we release a new version of the spec it should be possible to automatically have most of the SDK code updated automatically, with some test code/data requiring manual updates. I'm not sure what would be the best way of achieving that in Java, I only hope that using Java 8 won't be an obstacle.

**Comment by aalmiray** [comment]
Source code generation should not be a problem when using an external format which I suppose the spec will provide. 

Source code generation within the Java language is usually (but not restricted to) annotation processors. This of course requires writing Java code (processor) that takes annotated Java code as inputs to generate yet more Java code.

Thus I suppose choosing an external file template engine that   works best with all cdevents sdk targets would be the best option.
