### ISSUE TITLE
Tag and release to GitHub

### ISSUE THREAD

**Issue by aalmiray** [cdevents/sdk-java#22]
Followup to #9 

Current settings found at `pom.xml` and `release.yml` workflow perform the following tasks:
- update version to a given input and commit changes.
- publish JARs and POM to Maven Central.

I'd suggest enhancing the release setup to also perform the following tasks:
- tag the release
- create a GitHub release
- [optional] announce the release on Twitter, Slack, etc

[JReleaser](https://jreleaser.org) may be used to provide such behavior.
Releases could look like this https://github.com/kordamp/kordamp-maven-parent/releases/tag/v1.3.0
Such release was created with the following input files:
- [configuration](https://github.com/kordamp/kordamp-maven-parent/blob/main/jreleaser.yml)
- [workflow](https://github.com/kordamp/kordamp-maven-parent/blob/main/.github/workflows/release.yml)

JReleaser may be configured as a Maven plugin as well, avoiding the need to installing the CLI tool. If a commit message format convention is applied to the project (such as [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/)) then the generated changelog may look a bit better (categories, scopes, etc). Custom conventions may be mapped as well.

**Comment by elmsdata** [comment]
I've never heard of JReleaser and looks like a great plugin! I like the breakdown of the changelog and individual commits on the version you linked. 😄 I would also recommend looking at autogenerating a changelod.md file and a I found a NPM plugin that is used in many other projects regardless of the language! It's easy to import to a project using Github Actions. I almost have it working on the python SDK, you can see [on line 28](https://github.com/cdevents/sdk-python/blob/main/.github/workflows/pypi-release.yml#L28)!

**Comment by aalmiray** [comment]
JReleaser offers more options for configuring the changelog. https://jreleaser.org/guide/latest/reference/release/changelog.html
