### ISSUE TITLE
Update Java SDK to CDEvents spec v0.2

### ISSUE THREAD

**Issue by afrittoli** [cdevents/sdk-java#27]
Spec: https://github.com/cdevents/spec/tree/v0.2.0

**Comment by elmsdata** [comment]
Just saw this issue and realize I could loop in [my issue here](https://github.com/cdevents/sdk-java/issues/32) into your overall issue when updating the pom.xml! May just start with `0.0.1` to validate the automation then release `0.0.2` after confirming we can pull the dependency for the Jenkins plugin.

**Comment by rjalander** [comment]
The current Java SDK is compatible with CDEvents v0.1.2, PR https://github.com/cdevents/sdk-java/pull/58 is created to generate the SDK from the jsonschema, once the PR is merged we could be able to generate Java SDK v0.2.0, v0.3.0, etc.

**Comment by rjalander** [comment]
The changes merged to Generate SDK with v0.3.0 spec https://github.com/cdevents/sdk-java/pull/62
As we have v0.3.0 is the latest version of spec, not creating SDK with v0.2.0 and closing this issue.
