### ISSUE TITLE
Java SDK tests against schemas and examples in the spec repo

### ISSUE THREAD

**Issue by afrittoli** [cdevents/sdk-java#28]
The Java SDK should include tests that:
- events produced by the SDK match the [jsonschemas](https://github.com/cdevents/spec/tree/v0.2.0/schemas) defined in the spec repo
- it is possible to produce the [examples](https://github.com/cdevents/spec/tree/v0.2.0/examples) in the spec repo using the Java SDK

**Comment by rjalander** [comment]
The [unit tests](https://github.com/cdevents/sdk-java/blob/main/sdk/src/test/java/dev/cdevents/CDEventsTest.java) created have the validation to test the events against schemas.
Need to work on adding tests to produce the examples.
