### ISSUE TITLE
Redundant event type parameter in the API

### ISSUE THREAD

**Issue by afrittoli** [cdevents/sdk-java#33]
To create a CDEvent with the Java SDK, I can do:
```
            CloudEvent prfe = CDEventTypes.createPipelineRunFinishedEvent(
                CDEventConstants.CDEventTypes.PipelineRunFinishedEvent.getEventType(),
                "id", uri, "name", uri,
                        CDEventConstants.Outcome.OutcomeSuccess, "errors", "data");
```

The first parameter requires is the type, but that seems redundant since the create methods are client specific anyways

**Comment by rjalander** [comment]
With this way of creating an event is not as per the latest specification, this will be solved with the Refactoring PR:  https://github.com/cdevents/sdk-java/pull/35/files
