### ISSUE TITLE
CDEvents generator using jsonschema

### ISSUE THREAD

**Issue by rjalander** [cdevents/sdk-java#46]
All the [events](https://github.com/cdevents/sdk-java/tree/main/src/main/java/dev/cdevents/events) created manually in the SDK, needs to be generated based on [schemas](https://github.com/cdevents/spec/tree/main/schemas) spec version.

Can be implemented similar to what we have in go-sdk [generator](https://github.com/cdevents/sdk-go/tree/main/tools)

**Comment by rjalander** [comment]
Initial PR created to address this issue, pending for approval; https://github.com/cdevents/sdk-java/pull/58

**Comment by afrittoli** [comment]
@rjalander can this be closed now?

**Comment by rjalander** [comment]
The CDEvents generator created with the below PRs, closing the issue.
https://github.com/cdevents/sdk-java/pull/58
https://github.com/cdevents/sdk-java/pull/60
